<p>To join our mailing list and keep up-to-date with all the latest in the Circuit Records stable fill in and submit the form below.</p>
<form method="post" action="http://sugarmail.llamaweb.co.uk/box.php" target="_blank">
    <input name="p" type="hidden" id="p" value="9">
    <input type="hidden" name="nlbox[1]" value="4">
	<div class="form_field"><label for="email" class="form_desc">Email: <span class="required">(required)</span></label><input class="form_content textfield" type="text" name="email" /></div>
	<div class="form_field"><label for="name" class="form_desc">Name: <span class="required">(required)</span></label><input class="form_content textfield" type="text" name="name" /></div>
   	<div class="form_field">
        <label class="form_desc"><input name="funcml" type="radio" value="add" checked="checked"> Subscribe</label>
        <label class="form_desc"><input name="funcml" type="radio" value="unsub2"> Unsubscribe</label>
   	</div>
	<div class="form_base">
	   <input type="submit" name="Submit" value="Submit" class="submitbutton" />
    </div>
</form>