<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=$this->metaTitle?></title>
<meta name="keywords" content="<?=$this->metaKeywords?>" />
<meta name="description" content="<?=$this->metaDescription?>" />
<link rel="shortcut icon" href="/images/ACTIVE.ico" />
<link rel="stylesheet" type="text/css" href="/css/page-format.css" />
<link rel="stylesheet" type="text/css" href="/css/stylesheet.css" />
<script type="text/javascript" src="/js/jquery-1.4.4.js"></script>
<?php foreach ($this->css as $css):?>
    <link rel="stylesheet" type="text/css" href="<?=htmlentities($css, ENT_QUOTES, 'UTF-8')?>" />
<?php endforeach;?>
<?php foreach ($this->headJs as $headJs):?>
    <script src="<?=htmlentities($headJs, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>
</head>

<body>
<div id="page">
    <div id="content_wrapper">
        <div id="header">
            <p id="logo"><img src="/images/logo.jpg" alt="Ray Kohn" width="299" height="110" /></p>
            <ul id="nav">
                <li><a href="/">HOME</a></li>
                <li><a href="/view/bedroom-1">BEDROOM 1</a></li>
                <li><a href="/view/bedroom-2">BEDROOM 2</a></li>
                <li><a href="/view/bedroom-3">BEDROOM 3</a></li>
                <li class="noborder"><a href="/view/bedroom-4">BEDROOM 4</a></li>
                <li><a href="/view/gallery">GALLERY \ HALLWAY</a></li>
                <li><a href="/view/library">LIBRARY</a></li>
                <li><a href="/view/music-room">MUSIC ROOM</a></li>
                <li><a href="/view/shed">SHED</a></li>
                <li class="noborder"><a href="/contact">CONTACT US</a></li>
            </ul>
        </div>
        
        <div id="main_content">
            <?=$this->page_title ? '<h1>' . $this->page_title . '</h1>' : '';?>
			<?php
            if ($this->contentView):
                if ($file = $this->_script($this->contentView)):
                        include $file;
                endif;
            else:
                echo $this->content;
            endif;
        	?>
    	</div>
                
        <div id="footer">
            <p>Address and other necessary details to go in here</p>
            <p>Website designed and built by <a href="http://www.sugarcaneweb.co.uk">www.sugarcaneweb.co.uk</a></p>
        </div>
    </div>
</div>
<?php foreach ($this->js as $js):?>
    <script src="<?=htmlentities($js, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>
</body>
</html>