<h1>Initial Enquiry</h1>
<table cellspacing="0" class="admintable">
    <tr>
        <td class="tabledesc">Registered Name of Applicant Organisation:</td>
        <td><?=$this->applicationForm['organisation']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Address:</td>
        <td><?=$this->applicationForm['address']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Postcode:</td>
        <td><?=$this->applicationForm['postcode']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Name of main contact:</td>
        <td><?=$this->applicationForm['main_contact']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Telephone:</td>
        <td><?=$this->applicationForm['phone']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Mobile Telephone:</td>
        <td><?=$this->applicationForm['mobile']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Email:</td>
        <td><?=$this->applicationForm['email']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Legal Status of Organisation<br />e.g. Company limited by guarantee, Industrial &amp; Provident Society, CIC etc:</td>
        <td><?=$this->applicationForm['legal_status']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Company No:</td>
        <td><?=$this->applicationForm['company_number']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Charity No. (If applicable):</td>
        <td><?=$this->applicationForm['charity_number']?></td>
    </tr>
    <tr>
        <td class="tabledesc">How long has the organisation been established?:</td>
        <td><?=$this->applicationForm['established']?></td>
    </tr>
    <tr>
        <td colspan="2" class="desc">Funding required from Key Fund:</td>
    </tr>
    <tr>
        <td class="tabledesc">Total amount:</td>
        <td>&pound;<?=$this->applicationForm['total_amount']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Grant:</td>
        <td>&pound;<?=$this->applicationForm['grant']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Loan:</td>
        <td>&pound;<?=$this->applicationForm['loan']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Equity:</td>
        <td>&pound;<?=$this->applicationForm['equity']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Other:</td>
        <td>&pound;<?=$this->applicationForm['other']?></td>
    </tr>
    <tr>
        <td class="tabledesc">If other, please describe:</td>
        <td><?=$this->applicationForm['other_description']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Proposed Repayment Period:</td>
        <td><?=$this->applicationForm['repayment_period']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Please give a brief description of your enterprise activity/idea:</td>
        <td><?=$this->applicationForm['enterprise_idea']?></td>
    </tr>
    <tr>
        <td class="tabledesc">In a few words describe what makes the organisation a Social Enterprise:</td>
        <td><?=$this->applicationForm['social_enterprise']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Briefly describe what the Key Fund monies will be spent on:</td>
        <td><?=$this->applicationForm['money_spent_on']?></td>
    </tr>
    <tr>
        <td colspan="2"><strong>List the names of the three key people in the organisation and very briefly state their skills and experience</strong></td>
    </tr>
    <tr>
        <td class="tabledesc">Person 1</td>
        <td><?=$this->applicationForm['name_1']?> (<?=$this->applicationForm['skills_1']?>)</td>
    </tr>
    <tr>
        <td class="tabledesc">Person 2</td>
        <td><?=$this->applicationForm['name_2']?> (<?=$this->applicationForm['skills_2']?>)</td>
    </tr>
    <tr>
        <td class="tabledesc">Person 3</td>
        <td><?=$this->applicationForm['name_3']?> (<?=$this->applicationForm['skills_3']?>)</td>
    </tr>
    <tr>
        <td class="tabledesc">Who benefits from the work undertaken by the organisation and which communities do you serve?:</td>
        <td><?=$this->applicationForm['who_benefits']?></td>
    </tr>
    <tr>
        <td class="tabledesc">How did you hear about the Key Fund?:</td>
        <td><?=$this->applicationForm['how_hear']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Your Name:</td>
        <td><?=$this->applicationForm['name']?></td>
    </tr>
    <tr>
        <td class="tabledesc">Position or role within Organisation:</td>
        <td><?=$this->applicationForm['position']?></td>
    </tr>
</table>

<p><a class="button" style="width: 100px;">Accept Application</a> <a class="button" style="width: 100px;">Reject Application</a></p>
