<h1>Sugarcane Web Content Management System</h1>
<p>Welcome to the Sugarcane Web Content Management System.<br /><br /><br />
    Your options within the system are shown in the top right of this screen, so please do select an option from there.<br /></p><br /><h2>Your options within the system are:</h2>
    <p><strong>Content Editor</strong><br />
    <strong>Editable Regions</strong><br />
    <strong>Application Form Approvals</strong><br />
    <strong>News</strong><br />
    Click on the links in the top right to enter each section.
</p>
