<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <title>Sugarcane Web CMS</title>
    <link rel="stylesheet" type="text/css" href="/css/default.css" />
	<link rel="shortcut icon" href="SUGARCANE_WEB.ico" />
    <?php foreach ($this->css as $css):?>
        <link rel="stylesheet" type="text/css" href="<?=htmlentities($css, ENT_QUOTES, 'UTF-8')?>" />
    <?php endforeach;?>
    <?php foreach ($this->headJs as $headJs):?>
        <script src="<?=htmlentities($headJs, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
    <?php endforeach;?>
    <script type="text/javascript" src="/js/jquery-1.4.4.js"></script>
</head>

<body>
    <div id="page">
        <div id="header">
            <!-- <img src="url(/images/weblynx.jpg" alt="weblynx" width="169" height="52" /> -->
            <a target="_blank" href="http://www.sugarcaneweb.co.uk"><img src="/images/SUGARCANE_WEB_ADMIN_LOGO.png" alt="sugarcane_web" /></a>
            <ul id="nav">
                <li><a href="/admin/">CMS Home</a></li>
                <li><a href="/admin/users.php">Users</a></li>
                <li><a href="/pagebuilder/">Content</a></li>
                <li><a href="/admin/editableregions/">Editable Regions</a></li>
                <li><a href="/admin/applications/">Form Approval</a></li>
                <li><a href="/blogadmin/">News</a></li>
                <li><a href="/admin/login.php?do=logout">Logout</a></li>
            </ul>
        </div>
        
        <div id="content">
            <?php
                if ($this->contentView):
                    if ($file = $this->_script($this->contentView)):
                            include $file;
                    endif;
                else:
                    echo $this->content;
                endif;
            ?>
        </div>
    </div>
    
    <?php foreach ($this->js as $js):?>
        <script src="<?=htmlentities($js, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
    <?php endforeach;?>
</body>
</html>