<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=$this->metaTitle?></title>
<meta name="keywords" content="<?=$this->metaKeywords?>" />
<meta name="description" content="<?=$this->metaDescription?>" />
<link rel="stylesheet" type="text/css" href="/css/stylesheet.css" />
<!-- <link rel="stylesheet" type="text/css" href="/css/homepage.css" /> -->
<?php foreach ($this->css as $css):?>
    <link rel="stylesheet" type="text/css" href="<?=htmlentities($css, ENT_QUOTES, 'UTF-8')?>" />
<?php endforeach;?>
<?php foreach ($this->headJs as $headJs):?>
    <script src="<?=htmlentities($headJs, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>
</head>

<body>
<div id="header_wrapper">
    <div id="header">
        <h1 id="strapline">Investing in Social Enterprise</h1>
        <a href="/"><img src="/images/logo.png" alt="Key Fund" width="334" height="140" /></a>
        <div id="header_images">
            <?php $i = 1; foreach($this->header_images as $image): ?>
                <?php if($image['url']): ?><a href="<?=$image['url']?>" target="_blank"><?php endif; ?>
                    <div class="imagewrapper<?=($i == count($this->header_images)) ? ' last' : ''?>"><img width="176" height="176" src="/images/header-images/<?=$image['image']?>" alt="" /></div>
                <?php if($image['url']): ?></a><?php endif; ?>
            <?php $i++; endforeach; ?>
        </div>
    </div>
</div>

<div id="nav_wrapper">
    <ul id="nav">
        <?=$this->nav?>
    </ul>
</div>

<div id="content_wrapper">
    <div id="content">
        <div id="content_left">
            <?php foreach($this->latestposts as $post): ?>
                <div class="home_blogpost">
                    <a href="/blog/view/<?=$post['post_id']?>"><h2 class="blogtitle"><?=$post['post_title']?></h2></a>
                    <a href="/blog/view/<?=$post['post_id']?>"><img style="border: 3px solid #fff;" width="690px" src="/images/blogimages/<?=$post['post_image']?>" alt="<?=$post['post_title']?>" /></a>
                    <p style="font-size: 15px;"><?=$post['post_summary']?></p>
                    <p><a href="/blog/view/<?=$post['post_id']?>" class="readmore">Click here for more...</a></p>
                </div>
            <?php endforeach; ?>
            <?php
            if ($this->contentView):
                if ($file = $this->_script($this->contentView)):
                        include $file;
                endif;
            else:
                echo $this->content;
            endif;
            ?>
        </div>
        
        <div id="content_right">
            <h2 style="margin-left: 13px;">Case Studies</h2>
            <div id="sidebar_content">
                <p id="sb_map"><a href="/view/investments-by-region-"><img src="/images/map.jpg" alt="map" width="218" height="291" /></a></p>
                <a href="/view/finance-packages"><div class="box">
                    <p class="header">Finance Packages</p>
                    <p>Click here to learn<br />more about our finance packages</p>
                </div></a>
                <p id="sb_newsletter"><a href="/view/subscribe"><img src="/images/newsletter.png" alt="Signup for our newsletter" width="209" height="64" /></a></p>
                <a href="/view/apply-now"><div class="box" style="background: url(/images/sidebar_box_2.png) top left no-repeat;">
                    <p class="header">Apply Now</p>
                    <p>Click here to<br />apply through Key Fund</p>
                </div></a>
                <div id="sb_editablecontent">
                    <?=$this->sidebarEditableRegion?>
                </div>
                <img src="/images/logo.png" alt="Key Fund" width="209" height="87" id="sb_logo" />
            </div>
            <p id="sb_phone">0845 140 1400</p>
        </div>
    </div>
</div>

<div id="footer_wrapper">
    <div id="footer">
        <div id="footerlogos_editablecontent">
            <?=$this->footerLogosEditableRegion?>
        </div>
        <div id="footer_editablecontent">
            <?=$this->footerEditableRegion?>
        </div>
    </div>
</div>
<?php foreach ($this->js as $js):?>
    <script src="<?=htmlentities($js, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>
</body>
</html>