<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=$this->metaTitle?></title>
<meta name="keywords" content="<?=$this->metaKeywords?>" />
<meta name="description" content="<?=$this->metaDescription?>" />
<?php foreach ($this->css as $css):?>
    <link rel="stylesheet" type="text/css" href="<?=htmlentities($css, ENT_QUOTES, 'UTF-8')?>" />
<?php endforeach;?>
<script type="text/javascript" src="/js/jquery-1.4.2.min.js"></script>
<?php foreach ($this->headJs as $headJs):?>
    <script src="<?=htmlentities($headJs, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>
</head>

<body>
<div id="cmsbarwrapper">
    <div id="cmsbar">
        <p style="text-align: right;"><img width="126" height="39" src="/images/weblynx.jpg" alt=""><span class="closewindow">[x] close preview</span></p>
    </div>
</div>

<div id="page">
    <div id="header">
        <img src="/images/weblynx.jpg" alt="weblynx" width="169" height="52" />
    </div>
    
    <ul id="nav">
        <?=$this->nav?>
    </ul>

    <div id="content">
        <?=$this->page_title ? '<h1>' . $this->page_title . '</h1>' : '';?>
        <?php
            if ($this->contentView):
                if ($file = $this->_script($this->contentView)):
                        include $file;
                endif;
            else:
                echo $this->content;
            endif;
        ?>
    </div>
</div>
<?php foreach ($this->js as $js):?>
    <script src="<?=htmlentities($js, ENT_QUOTES, 'UTF-8')?>" type="text/javascript"></script>
<?php endforeach;?>
</body>
</html>