<form method="post" action="https://www.thekeyfund.co.uk/apply/savepartone/" enctype="multipart/form-data">
    <div class="form_field">
        <label class="form_desc" for="organisation">Registered Name of Applicant Organisation: <span class="required">(required)</span></label>
        <input type="text" value="" name="organisation" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="address">Address: <span class="required">(required)</span></label>
        <textarea name="address" class="form_content textarea"></textarea>
    </div>
    <div class="form_field">
        <label class="form_desc" for="postcode">Postcode: <span class="required">(required)</span></label>
        <input type="text" value="" name="postcode" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="main_contact">Name of main contact: <span class="required">(required)</span></label>
        <input type="text" value="" name="main_contact" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="phone">Telephone: <span class="required">(required)</span></label>
        <input type="text" value="" name="phone" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="mobile">Mobile Telephone: <span class="required">(required)</span></label>
        <input type="text" value="" name="mobile" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="email">Email: <span class="required">(required)</span></label>
        <input type="text" value="" name="email" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="legal_status">Legal Status of Organisation<br />e.g. Company limited by guarantee, Industrial &amp; Provident Society, CIC etc: <span class="required">(required)</span></label>
        <input type="text" value="" name="legal_status" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="company_number">Company No: <span class="required">(required)</span></label>
        <input type="text" value="" name="company_number" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="charity_number">Charity No. (If applicable):</label>
        <input type="text" value="" name="charity_number" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="established">How long has the organisation been established?:</label>
        <input type="text" value="" name="established" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc">Funding required from Key Fund:</label>
        <label class="inline_desc" for="total_amount">Total amount:</label>
        &pound; <input type="text" value="" name="total_amount" class="form_content textfield funding_textfield"> <span><strong>comprising of</strong></span><br />
        <div id="funding_inputs">
            <label class="inline_desc" for="grant">Grant:</label>
            &pound; <input type="text" value="" name="grant" class="form_content textfield funding_textfield">
            <label class="inline_desc" for="loan">Loan:</label>
            &pound; <input type="text" value="" name="loan" class="form_content textfield funding_textfield">
            <label class="inline_desc" for="equity">Equity:</label>
            &pound; <input type="text" value="" name="equity" class="form_content textfield funding_textfield">
            <label class="inline_desc" for="other">Other:</label>
            &pound; <input type="text" value="" name="other" class="form_content textfield funding_textfield">
        </div>
    </div>
    <div class="form_field">
        <label class="form_desc" for="other_description">If other, please describe:</label>
        <input type="text" value="" name="other_description" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="repayment_period">Proposed Repayment Period:</label>
        <input type="text" value="" name="repayment_period" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="enterprise_idea">Please give a brief description of your enterprise activity/idea: <span class="required">(required)</span></label>
        <textarea name="enterprise_idea" class="form_content textarea"></textarea>
    </div>
    <div class="form_field">
        <label class="form_desc" for="social_enterprise">In a few words describe what makes the organisation a Social Enterprise: <span class="required">(required)</span></label>
        <textarea name="social_enterprise" class="form_content textarea"></textarea>
    </div>
    <div class="form_field">
        <label class="form_desc" for="money_spent_on">Briefly describe what the Key Fund monies will be spent on: <span class="required">(required)</span></label>
        <textarea name="money_spent_on" class="form_content textarea"></textarea>
    </div>
    <p><strong>List the names of the three key people in the organisation and very briefly state their skills and experience</strong></p>
    <div class="form_field">
        <label class="form_desc" for="name_1">Name:</label>
        <input type="text" value="" name="name_1" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="skills_1">Skills/Experience:</label>
        <input type="text" value="" name="skills_1" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="name_2">Name:</label>
        <input type="text" value="" name="name_2" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="skills_2">Skills/Experience:</label>
        <input type="text" value="" name="skills_2" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="name_3">Name:</label>
        <input type="text" value="" name="name_3" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="skills_3">Skills/Experience:</label>
        <input type="text" value="" name="skills_3" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="who_benefits">Who benefits from the work undertaken by the organisation and which communities do you serve?: <span class="required">(required)</span></label>
        <textarea name="who_benefits" class="form_content textarea"></textarea>
    </div>
    <div class="form_field">
        <label class="form_desc" for="how_hear">How did you hear about the Key Fund?: <span class="required">(required)</span></label>
        <textarea name="how_hear" class="form_content textarea"></textarea>
    </div>
    <p id="formuploads">Please upload the following with your application. Please note your application will be delayed if we do not receive all of the documentation needed.</p>
    <div class="form_field">
        <label class="inline_desc" for="governing_doc" style="display: inline-block; width: 270px;">Governing document:</label>
        <input type="file" name="governing_doc" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="inline_desc" for="state_aid" style="display: inline-block; width: 270px;">State Aid Proforma:</label>
        <input type="file" name="state_aid" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="inline_desc" for="annual_accounts" style="display: inline-block; width: 270px;">Last 2 years annual accounts:</label>
        <input type="file" name="annual_accounts" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="inline_desc" for="trading_figures" style="display: inline-block; width: 270px;">Latest trading figures:</label>
        <input type="file" name="trading_figures" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="inline_desc" for="bank_declined" style="display: inline-block; width: 270px;">Evidence that a Bank has declined to lend:</label>
        <input type="file" name="bank_declined" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="inline_desc" for="bank_statements" style="display: inline-block; width: 270px;">Last 3 months Bank Statements (copies):</label>
        <input type="file" name="bank_statements" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="name">Your Name:</label>
        <input type="text" value="" name="name" class="form_content textfield">
    </div>
    <div class="form_field">
        <label class="form_desc" for="position">Position or role within Organisation:</label>
        <input type="text" value="" name="position" class="form_content textfield">
    </div>
<!--
    <div class="form_field">
        <label class="form_desc" for="date">Date:</label>
        <input type="text" value="<?=date('d/m/Y')?>" name="date" disabled="disabled" class="form_content textfield">
    </div>
-->
    <div class="submitarea">
        <input type="submit" value="Submit Application" />
    </div>
</form>

